Update check-aggregate.rb to support honor-stash
sensu-plugins/sensu-plugins-sensu pull request #17
Opened 2016-07-25 20:37 UTC by bfloyd89

## Pull Request Checklist

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

#### Purpose
The honor-stash function needs a list of maps with check/client/status information. This change includes the queries to add that information to when calling the named_aggregate_results function.

I'm not a very experienced ruby programmer so feel free to reject and treat this as a bug report.

2017-05-29 04:57 UTC, majormoses commented
@bfloyd89 could you take a look at failing CI?

2017-05-29 15:31 UTC, bfloyd89 commented
@majormoses done

2017-05-29 15:38 UTC, majormoses commented
@bfloyd89 looks like there are still some CI issues, could you take a look at that?

2017-05-29 16:11 UTC, bfloyd89 commented
@majormoses yep, sorry, done

2017-05-29 16:27 UTC, majormoses requested changes

2017-05-29 16:27 UTC, majormoses commented on bin/check-aggregate.rb
> +    if results[:critical] > 0
We should use unknown in the case of a negative number (I know not likely but false positives often seem to these silly little error handling)

2017-05-29 16:27 UTC, majormoses commented on bin/check-aggregate.rb
> +    if results[:critical] > 0
Also is there a reason this is not an if elsif block currently? I think the next if should be part of an if/elsif block unless I am missing something as I dont see the value in checking again.

2017-05-29 16:34 UTC, majormoses commented on bin/check-aggregate.rb
> +    if results[:critical] > 0
I think I am can you post an example response back?

2017-07-09 16:37 UTC, majormoses commented
@bfloyd89 are you planning on seeing this through to completion?

2017-07-20 01:22 UTC, majormoses commented
closing due to inactivity

2017-07-20 01:22 UTC, closed without merging