update the aggregate metric to the latest api
sensu-plugins/sensu-plugins-sensu pull request #21
Opened 2016-12-07 07:15 UTC by oba11

## Pull Request Checklist

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### Purpose

The old aggregate metrics doesnt work with pre 0.24 and named aggregates introduced later which was fixed by this script.

#### Known Compatablity Issues

Not compatible with sensu-api older than 0.24

2017-04-28 17:15 UTC, envintus commented
@portertech Any chance that this is still good to be merge pending someone like you in the know is able to vette it? I have a need for this, but would like to avoid running a custom implementation if at all possible. Pulling from this repo would be preferred. Thanks!

2017-06-24 19:31 UTC, majormoses commented
please rebase then I will take a look.

2017-06-25 01:47 UTC, majormoses requested changes
make breaking changes more obvious in CHANGELOG and rebase other than that this looks good.

2017-06-25 01:47 UTC, majormoses commented on CHANGELOG.md
> +- metrics-aggregates.rb: Refactored to support new named aggregates introduced in Sensu 0.24
This is a breaking change, please put it under a `### Breaking Changes` header under `## [Unreleased]`

2017-07-20 01:27 UTC, majormoses commented
closing due to inactivity, please reply back if you would like to see this through so I can re-open.

2017-07-20 01:27 UTC, closed without merging