Add support for client invalidation in the deregister handler
sensu-plugins/sensu-plugins-sensu pull request #23
Opened 2017-03-27 20:22 UTC by Evesy

## Pull Request Checklist

Add CLI options to deregister handler to set invalidate & invalidate_duration parameters.

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose

In the upcoming 0.29 Sensu Core release deleting a client via the API will provide additional parameters to invalidate a clients results until it is successfully deleted from the registry, or invalidate a client results until a specified duration has passed -- See https://github.com/sensu/sensu/pull/1640

To make use of this functionality when the release is out the deregister handler needs a method to expose those options.

#### Known Compatablity Issues

This is backwards compatible with Sensu <0.29 as the additional URL parameters are simply ignored.

2017-03-28 18:44 UTC, cwjohnston commented
@Evesy thanks for this contribution, I think this looks great! I will find some time to test your changes in my lab 👍

2017-05-29 04:13 UTC, majormoses approved these changes
LGTM

2017-05-29 04:13 UTC, majormoses commented
@cwjohnston any progress on testing this?

2017-06-25 01:39 UTC, majormoses requested changes
This is a breaking change and does not need to be.

2017-06-25 01:39 UTC, majormoses commented on bin/handler-sensu-deregister.rb
> +    else
this changes the default behavior (making it a breaking change) you can avoid this by adding another elsif with what you have below and an else with the old api request.

2017-06-25 11:43 UTC, Evesy commented
@majormoses Had forgot to consider those not wanting to use client invalidation! Does this change look better now?

2017-06-25 14:20 UTC, majormoses commented
@Evesy yup, thanks for the quick turn around this looks safe so I will merge and release it.

2017-06-25 14:20 UTC, majormoses approved these changes

2017-06-25 14:20 UTC, merged

2017-06-25 14:50 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-sensu/versions/1.1.0