Add ignore-severity option
sensu-plugins/sensu-plugins-sensu pull request #27
Opened 2017-06-14 09:12 UTC by Moozaliny

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### Purpose

Changes the default behaviour to alert with the severity of the aggregated checks. The ignore-severity option allows to ignore the severities and just alert (like before) based on the amount of non-ok.

We need the functionality to only exit with critical when there are enough critical checks. To alert based on non-ok is not enough for us.

I am open for other suggestions to solve this issue.

2017-06-24 16:24 UTC, majormoses requested changes
I do not have access to this repo so someone else needs to review but this is a breaking change and I do not know if they will even accept it but minimally it needs to be called out louder that this is a breaking change so maintainers can more easily figure out the next release version and for users to quickly spot and evaluate breaking changes.

2017-06-24 16:24 UTC, majormoses commented on CHANGELOG.md
> +- check-aggregates.rb: Changed the default behaviour to alert with the severity of the aggregated checks.
Breaking change, please break out into a header of `### Breaking Change` under `## [Unreleased]`.

2017-07-10 12:47 UTC, Moozaliny commented
Thanks for taking a look! Another option would be, to keep the current default behaviour and add a flag to take severities into account.

If you like this more, the descriptions for `warning_count` and `critical_count` should be fixed.

2017-07-10 15:39 UTC, majormoses commented
I guess I would like to understand the intended use case better as it feels like the current options do not align with the goals so let's take a step back and discuss how it should ideally work and then we can figure out how to get there. Can you open an issue to continue discussion there and link to the PR?

2017-07-21 19:19 UTC, majormoses commented
@Moozaliny sorry for the delay on this I will review this closer this weekend and hopefully merge & release.

2017-08-20 15:54 UTC, majormoses commented
Sorry this fell off my radar I will get to it today. I fixed up the merge conflicts.

2017-08-20 15:55 UTC, majormoses approved these changes
LGTM

2017-08-20 15:55 UTC, merged

2017-08-20 16:01 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-sensu/versions/2.0.0