Stale option
sensu-plugins/sensu-plugins-sensu pull request #40
Opened 2017-09-11 20:51 UTC by rbanffy

## Pull Request Checklist

**Is this in reference to an existing issue?**

No.

#### General

- [X] Update Changelog following the conventions laid out on [Our CHANGELOG Guidelines ](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [X] Update README with any necessary configuration snippets

- [X] Binstubs are created if needed

- [X] RuboCop passes

- [X] Existing tests pass

#### New Plugins

- [N/A] Tests

- [N/A] Add the plugin to the README

- [N/A] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

Issue a warning if the number of stale checks go over a specified count.

#### Known Compatibility Issues

None.

2017-09-13 09:01 UTC, luisdavim approved these changes
LGTM

2017-09-13 13:42 UTC, rbanffy commented
Reduced the number of commits by changing the past.

2017-09-14 23:17 UTC, majormoses requested changes
Overall this looks good, the thing I think we can improve here is the name of the options.

2017-09-14 23:17 UTC, majormoses commented on bin/check-aggregate.rb
> +  option :stale,
if we are going to use `--stale-count` then I think this should be `--stale-percentage` as looking at the 2 options before reading the description I assumed it was any stale seeing both `--stale` and `--stale-count`

2017-09-16 16:13 UTC, majormoses approved these changes
LGTM

2017-09-16 16:14 UTC, merged

2017-09-16 16:46 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-sensu/versions/2.2.0