Removed broken and unnecessary block argument
sensu-plugins/sensu-plugins-sensu pull request #44
Opened 2017-09-25 19:31 UTC by portertech

The block argument should have been `&blk`. I removed it, as yield() is used making it unnecessary.

2017-09-25 22:37 UTC, majormoses requested changes
Just need a changelog entry per: https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md

2017-09-26 04:09 UTC, portertech commented
@majormoses added changelog entry 👍

2017-09-26 04:26 UTC, majormoses approved these changes
LGTM

2017-09-26 04:27 UTC, merged

2017-09-26 04:35 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-sensu/versions/2.2.1